In [1]:
import requests

In [2]:
from bs4 import BeautifulSoup

In [3]:
r = requests.get('https://www.yelp.com/biz/carmelinas-boston-2')

In [4]:
r.status_code

200

In [5]:
# r.text

In [6]:
soup = BeautifulSoup(r.text, 'html.parser')

In [7]:
answer=soup.findAll('span',class_="lemon--span__373c0__3997G raw__373c0__3rKqk")

In [9]:
# answer.text

In [10]:
review = []
for p in answer:
    review.append(p.text)

In [11]:
review

["Your trust is our top concern, so businesses can't pay to alter or remove their reviews. Learn more.",
 "Start your review of Carmelina's.",
 "We had an amazing experience at Carmelina's! Totally would recommend to anyone visiting or who lives here in Boston. My husband and I went with a couple of friends & everything we ordered was high quality. For apps we did fried calamari, garlic shrimp, & the brasato which were all tasty and big enough to share. For dinner we had carbonara, gnocchi al forno, and palermitana - all with perfectly cooked pasta and bursts of flavor. The gnocchi was hands down the best; perfect pillow-y potato dumplings and full of homemade sauce. One of the best things was the service. Our server, Anthony, was so kind and hospitable; he even told me the best way to heat up my leftovers the next day. Overall, our experience was great even with the restrictions needed for COVID-19 and hope to come back soon.",
 "Back in December, after multiple recommendations from friends to try Carmelina's, we decided to make a reservation. The soonest we could get a reservation for a Saturday night was three months later, on March 7th, which happened to fall between both of our birthdays, so while we had to wait, we had a great reason to celebrate. Little did we know, it would be the last time we would dine in a restaurant before they were all forced to close their doors due to the pandemic. We were a bit apprehensive because Carmelina's has a strict reservation policy and only allow 90 minutes for each reservation. We were worried that we'd feel rushed while out on a rare child-less date night, so we made sure to arrive right on time for our 6pm reservation. We were seated right away, but it took a few minutes to be greeted by our waiter. After looking over the menu, we ordered drinks (beer and wine only) and a couple of appetizers including the calamari and a baby eggplant special. The food was timed well and came out quickly, with the calamari being delivered first, which is when we ordered our entrees - the Sunday Macaroni and the highly recommended Crazy Alfredo. About halfway through eating the calamari, the eggplant arrived. Both were fantastic, but the eggplant was the stand-out. Only a few minutes later our entrees were delivered. This was the only time throughout our meal that we felt a bit rushed. We were still enjoying out appetizers and the waiter was trying to make room for our entrees on a small table. He asked if we were finished with the apps and when we said we were not, he offered to transfer them to smaller plates so they would fit on the table. We decided to split our entrees so we could each enjoy both. The Crazy Alfredo was like nothing we've ever had \xa0before. It was creamy, but not too heavy, with a bit of spice (but not too spicy) and tender pieces of chicken and sausage mixed in. It was the type of dish you'll think about months later. The Sunday Macaroni was massive - two homemade sausages, two meatballs, a huge short rib and a big pile of the most delicious housemade whipped ricotta over rigatoni. We asked for more bread for dipping in the Sunday sauce and it was amazing. The portions were very large and we did not feel rushed at all the rest of the meal. We ordered more drinks and were able to enjoy the rest of the dining experience at our own pace. Carmelina's does not serve dessert. They feel that they are experts in savory food and there are many options in the North End who are experts in a sweet ending to a meal. This allows them to seat more tables and excel in their craft. Overall, we had an excellent dining experience at Carmelina's - it was one of the best Italian meals I've ever had, including the many I've had in Italy during my travels over the years. Now that restaurants are starting to open their doors again, I highly recommend you visit Carmelina's for outdoor dining and help a small business recover from 3 months of lost business; just make a reservation first!",
 "Pre-Covid Review: Came here to celebrate my girlfriends birthday. It's a nice small restaurant. The food and service was amazing. The portions sizes were also very good. We got the Fried Calamari, Sunday Macaroni, and Fruity di Mare.",
 "While visiting Boston, we decided to have lunch in North End. This was recommended to us by my fianc√©'s father. It did NOT disappoint. The eggplant and mozzarella appetizer was unbelievable. For our entrees, we got the carbonara and the spaghetti \xa0with little neck clams in a white wine sauce. SO DELICIOUS! Thankfully, we walked plenty that day. :)",
 "My true rating would be a 4.5!Ive attempted to get a reservation at Carmelina's for the longest time but I was finally able to do it! I made the reservation through yelp and we were seated on their patio. The patio was really cute but the umbrellas could not cover all the tables. My seat/table, which were only partially covered, got extremely hot. The table was a metal table and I genuinely felt like I was getting burnt every time I accidentally touched it. But table/umbrella choice aside, the overall experience was great! Our server was attentive even though we were in the far end of the patio. My friend and I both ended up ordering the Gnocchi al forno so this review is just for the gnocchi. It was very good! The gnocchi was both chewy and firm (a little more firm that I would have liked). The portion was very generous that I had plenty of leftovers to take home. I wish the mozzarella was melted a little more to allow bigger cheese pull. The tomato sauce was very flavorful and the fresh basil was a cherry on top! I did notice a little pool of oil that maybe have come from the mozzarella.So if you do not want a really heavy meal, I highly suggest the gnocchi from Carmelina's.",
 "Great food, probably some of the best Chicken Parm I've ever had.Street dining setup would probably be fine when weather cooperates unfortunately, on our day Boston decided to have a record heat day (about 95 degrees at 6). Would be fabulous at 80 or below.",
 "While passing by I couldn't help but notice the appealing dishes being served. I tried to get a table but due to limited capacity and no reservation, I had to venture here the next night with a reservation.We started with the Mussels Marinara. The garlic marinara was so tasty. For entrees we ordered the Carbonara and Stuffed Center Cut Pork Rib Chop. They were both prepared to perfection! Carmelina's also has a great wine selection.I can see why the reviews are incredible for this restaurant. The food was incredible and the service impeccable.",
 "My taste buds were in heaven after I finally experienced the magical experience that is Carmelina's. I've had this place on my list pretty much since I moved to the city and even with all the hype from my friends, I was still pleasantly surprised with how much I enjoyed every aspect of my meal. I love writing 5-star reviews and this place definitely earned it.We started by ordering a bottle of the Montepulciano, the mussels and the garlic shrimp served in a pan. The sauces on our seafood were divine, I could have licked the garlic sauce right out of the pan. Very fresh and full of flavor. For our main entrees, we devoured the Penne Gorganzola and the Chicken Parm. The gorganzola sauce is rich and creamy without too strong of the cheese taste. It's fantastic. The chicken parm is definitely one of the best I've ever had the pleasure of trying - the meat was super tender and cooked perfectly. Given that everything we ordered turned out exceptional, I'd try anything on the menu.The ambiance was ideal, the outdoor seating is serene while still being able to take in the views of the North End. Out waiter Cesar was great, he gave awesome recommendations and was super attentive. I'm very much looking forward to my next visit!",
 "Expectations were far too high prior to coming. For the appetizer, we ordered Exploding Little Neck Clams and they were not cleaned properly (soooo much sand). The amount of sand in the clams were REPULSIVE. From that point on, I was already nervous to eat the shellfish from my Frutti Di Mare entree. Didn't know it automatically comes with capellini (thought it would be linguine). Would recommend substituting for a different pasta. Wasn't a fan of this dish! Would recommend ordering:BelliniCrazy Alfredo",
 'Amazing food and service! I can see why they are always so packed! We had the lamb to start. On point! I had a mushroom pasta and it was beyond delicious. Cant wait to come back again!',
 "We went for dinner the night after they reopened during COVID for outdoor seating. \xa0They have a bit of space cornered off in the street for dining but the tables are way less than 6ft apart. \xa0We tried to sit as far off to one side as we could but as our meal progressed they sat more and more people, but we know business are trying their best so we can't be too hard. \xa0The UFO beer was tasty as per our waiters recommendation, it was citrusy and light. \xa0 The Frose was just okay. \xa0 The food portions are huge and worth the price and equally as tasty. \xa0We had the Stuffed Pork Chop and the Pollo Cardinale ( this was the star of the show) \xa0and the sides were flavorful too. They don't do dessert so there is nothing to review there. \xa0 Service itself was good waiter was attentive and checked in on us but overall we wouldn't return here for dinner.",
 "Carmelina's is my favorite restaurant in the North End and one of my favorite restaurants period. This place is top notch. The space is clean, cozy (not too big and not too cramped), and even when it's packed with guests (which tends to be most evenings around dinner), you can still hear the person sitting across from you without having conversations like: Do you come here often? Yes, I'm doing great, thanks! Wait, what? Oh, I'm sorry, what?The food here is fantastic. Like, think about the best Italian meal you've ever had, but better. My friends and I have ordered a variety of items off the menu and everything has been amazing. Even my vegetarian friends (who have lived in Italy) came here and raved about their meals. Sometimes it's hard to get a reservation, so plan ahead!",
 "Seriously a fantastic meal. We started with the tuna appetizer which is on top of a bed of potatoes - sounds weird but it was incredible. After this we got the carbonara and lobster diavolo. Both pastas were insanely good. I almost got another popular pasta I believe it was a rigatoni, but the waitress informed me it was a strong blue cheese taste. Great service and atmosphere - I've been told by many this is the best spot for pasta in the north end and I have to agree ! Can't wait to go back.",
 'AMAZING FOOD!My go to place in the North End. Small and quaint with an open kitchen and super friendly staff!Scratch cooking with everything they offer. Your palate will be so happy for the fresh ingredients. Everyone has to eat here!',
 "Make a reservation or else you won't get to eat here. In fact, make a reservations weeks in advance! Carmelina's is a small restaurant in the North end with amazing Italian food. I've been here several times and have always been pleased with the food. There is a TV screen in here too if you want to watch sports.I love the fried calamari, its the perfect appetizer to share with the table. Its not overly covered in bread crumbs which is nice. I have had the frutti del mar past which comes with a generous amount of seafood. I also really enjoyed the Tonno con Pesto Siciliano e Fusilli- fussili pasta with tuna steak on top. I know this is a rather unusual dish but it was so good, sort of like east meet west in your pasta dish.Its also conveniently located close to Mike's Pastry so you can go there for dessert!",
 "BEST Italian in the North End, Hands Down. Everything Is superb! Better get a reservation. It's nigh to impossible to get a walk in, and for good reason. Not only is the food amazing, the service is spectacular! We've never had less than a perfect experience there.",
 "3.5*You should definitely make a reservation if you want to go; I personally would not think it'd be worth a wait if we didn't have a reservation. My friend made a reservation over a month in advance for Valentines weekend, and the only availability they had was Sunday afternoon at 1PM. We ordered the calamari, mushroom rigatoni, and frutti di mare. I would not recommend the calamari, that was probably my least favorite dish. I personally am not a fan on capers, and the calamari was more on the lighter, airy tasting side, which does not necessarily suit my tastes. Also, for $14, I personally did not think it was worth that price point, especially for the amount of food you get. The mushroom rigatoni was delicious - the different flavors melded together nicely with each bite, and the pasta was the perfect texture. This was our favorite dish of the evening. The frutti di mare was not by any means not yummy, but rather, after eating the seafood and eating a few bites, the flavor of the pasta became one note and tasted relatively the same with each bite, which was a little boring. The shrimp in the dish was also not flavored as well and tasted simply as though it was the texture of shrimp coated in a lighter marinara sauce. Not the most wow pasta experience I've had at the North End in Boston, and it would personally not be my first choice, but I would not mind going again.",
 'Late flight (less than 50% full) arrival from SFO, looking for dinner, got a great referral from hotel and Yelp. Walked over, 10 PM, kitchen still open!A few people at the bar, quick service, loquacious Italian server. Ordered branzino, and wife had amitriciana. So nice to get piping hot food. Servings, as usual in the north end, too big, branzino was well prepared, maybe a little too cooked, could have been firmer, pasta delicious. Nice bottle of elio Grasso 2018 Dolcetto. If we go back, we will be splitting the main, so we can try some antipasti.',
 "Carmelina's is the number one restaurant in the North End for a reason. \xa0Every time I go the food is perfect. \xa0My family was in town this weekend and it knocked their socks off. \xa0This is no easy feat since we are full Italian! \xa0Everything is made from scratch, even their stocks they cook with.We started with the Risotto Caprese and it was fantastic. \xa0This dish is basically caprese in risotto form. It was fresh and light and packed a ton of flavor! \xa0For our main dishes we ordered the baked 4 mushroom rigatoni, carbonara, Sundaymacaroni, and the penne capricciose. \xa0The hit of the dinner was the hit of the dinner! \xa0The sauce it came in was creamy and sweet, probably one of the best pasta dishes I've ever had.The food comes out whenever its ready and steaming hot! \xa0Our waiter was friendly and offered menu item suggestions based on our preferences! \xa0For drinks we ordered peach bellinis which was refreshing (and heavy on the champagne)! \xa0I will be coming back here because Carmelinas is a DREAM! \xa0Make reservations a couple weeks ahead of time because it fills up quick!",
 "The fettuccine Carmelina was perfecto! Great mix of seafood, chicken and sausage blended with a delicious red sauce. \xa0Get there early and be sure to order the mushroom and whipped goat cheese appetizer- you won't regret it!"]

In [12]:
#Analysis the Data

In [13]:
import pandas as pd
import numpy as np

In [14]:
df = pd.DataFrame(np.array(review), columns=['reviews'])

In [15]:
#df.head()

In [16]:
len(df['reviews'])

22

In [17]:
df['word_count'] = df['reviews'].apply(lambda x: len(x.split()))

In [18]:
#df.head

In [19]:
df['char_count'] = df['reviews'].apply(lambda x: len(x))

In [20]:
def average_words(x):
    words = x.split()
    return sum(len(word) for word in words) / len(words)

In [21]:
df['average_word_length'] = df['reviews'].apply(lambda x: average_words(x))

In [22]:
#counting the Stop words

In [23]:
from nltk.corpus import stopwords

In [24]:
stop_words = stopwords.words('english')

In [25]:
len(stop_words)

179

In [26]:
df['stopword_count'] = df['reviews'].apply(lambda x: len([word for word in x.split() if word.lower() in stop_words]))

In [27]:
df.head()

,reviews,word_count,char_count,average_word_length,stopword_count
0,"Your trust is our top concern, so businesses c...",18,100,4.611111,7
1,Start your review of Carmelina's.,5,33,5.800000,2
2,We had an amazing experience at Carmelina's! T...,141,795,4.645390,62
3,"Back in December, after multiple recommendatio...",554,3038,4.483755,280
4,Pre-Covid Review: Came here to celebrate my gi...,38,233,5.157895,14

In [28]:
df['stopword_rate'] =  df['stopword_count'] / df['word_count']

In [29]:
#df.head()

In [30]:
df.sort_values(by='stopword_rate')

,reviews,word_count,char_count,average_word_length,stopword_count,stopword_rate
7,"Great food, probably some of the best Chicken ...",45,257,4.733333,14,0.311111
19,Late flight (less than 50% full) arrival from ...,97,554,4.721649,33,0.340206
4,Pre-Covid Review: Came here to celebrate my gi...,38,233,5.157895,14,0.368421
21,The fettuccine Carmelina was perfecto! Great m...,37,223,5.027027,14,0.378378
0,"Your trust is our top concern, so businesses c...",18,100,4.611111,7,0.388889
1,Start your review of Carmelina's.,5,33,5.800000,2,0.400000
17,"BEST Italian in the North End, Hands Down. Eve...",47,265,4.659574,19,0.404255
10,Expectations were far too high prior to coming...,82,508,5.207317,34,0.414634
15,AMAZING FOOD!My go to place in the North End. ...,40,234,4.875000,17,0.425000
13,Carmelina's is my favorite restaurant in the N...,138,785,4.695652,60,0.434783
2,We had an amazing experience at Carmelina's! T...,141,795,4.645390,62,0.439716
20,Carmelina's is the number one restaurant in th...,190,1078,4.615789,85,0.447368
9,My taste buds were in heaven after I finally e...,220,1237,4.627273,99,0.450000
16,Make a reservation or else you won't get to ea...,153,817,4.346405,69,0.450980
14,Seriously a fantastic meal. We started with th...,96,498,4.197917,45,0.468750
5,"While visiting Boston, we decided to have lunc...",59,349,4.915254,28,0.474576
8,While passing by I couldn't help but notice th...,93,549,4.913978,46,0.494624
6,My true rating would be a 4.5!Ive attempted to...,222,1195,4.387387,112,0.504505
3,"Back in December, after multiple recommendatio...",554,3038,4.483755,280,0.505415
18,3.5*You should definitely make a reservation i...,253,1392,4.505929,128,0.505929
11,Amazing food and service! I can see why they a...,37,184,4.000000,19,0.513514
12,We went for dinner the night after they reopen...,162,848,4.172840,88,0.543210

In [31]:
df.describe()

,word_count,char_count,average_word_length,stopword_count,stopword_rate
count,22.000000,22.000000,22.000000,22.000000,22.000000
mean,123.954545,689.636364,4.695476,57.954545,0.439285
std,120.140187,655.934270,0.393999,61.424733,0.060155
min,5.000000,33.000000,4.000000,2.000000,0.311111
25%,41.250000,239.750000,4.489298,17.500000,0.401064
50%,94.500000,528.500000,4.652482,39.500000,0.443542
75%,159.750000,840.250000,4.904234,81.000000,0.489612
max,554.000000,3038.000000,5.800000,280.000000,0.543210

In [32]:
#Data Cleaning

In [33]:
df['lowercase'] = df['reviews'].apply(lambda x: " ".join(word.lower() for word in x.split()))

In [34]:
df.head()

,reviews,word_count,char_count,average_word_length,stopword_count,stopword_rate,lowercase
0,"Your trust is our top concern, so businesses c...",18,100,4.611111,7,0.388889,"your trust is our top concern, so businesses c..."
1,Start your review of Carmelina's.,5,33,5.800000,2,0.400000,start your review of carmelina's.
2,We had an amazing experience at Carmelina's! T...,141,795,4.645390,62,0.439716,we had an amazing experience at carmelina's! t...
3,"Back in December, after multiple recommendatio...",554,3038,4.483755,280,0.505415,"back in december, after multiple recommendatio..."
4,Pre-Covid Review: Came here to celebrate my gi...,38,233,5.157895,14,0.368421,pre-covid review: came here to celebrate my gi...

In [35]:
df['punctuation'] = df['lowercase'].str.replace('[^\w\s]', '')

In [36]:
from nltk.corpus import stopwords

In [37]:
stop_words = stopwords.words('english')

In [38]:
df['stopwords'] = df['punctuation'].apply(lambda x: " ".join(word for word in x.split() if word not in stop_words))

In [39]:
df.head()

,reviews,word_count,char_count,average_word_length,stopword_count,stopword_rate,lowercase,punctuation,stopwords
0,"Your trust is our top concern, so businesses c...",18,100,4.611111,7,0.388889,"your trust is our top concern, so businesses c...",your trust is our top concern so businesses ca...,trust top concern businesses cant pay alter re...
1,Start your review of Carmelina's.,5,33,5.800000,2,0.400000,start your review of carmelina's.,start your review of carmelinas,start review carmelinas
2,We had an amazing experience at Carmelina's! T...,141,795,4.645390,62,0.439716,we had an amazing experience at carmelina's! t...,we had an amazing experience at carmelinas tot...,amazing experience carmelinas totally would re...
3,"Back in December, after multiple recommendatio...",554,3038,4.483755,280,0.505415,"back in december, after multiple recommendatio...",back in december after multiple recommendation...,back december multiple recommendations friends...
4,Pre-Covid Review: Came here to celebrate my gi...,38,233,5.157895,14,0.368421,pre-covid review: came here to celebrate my gi...,precovid review came here to celebrate my girl...,precovid review came celebrate girlfriends bir...

In [40]:
pd.Series(" ".join(df['stopwords']).split()).value_counts()[:30]

would          15
food           15
carmelinas     15
reservation    15
end            12
ordered        12
pasta          12
best           11
north          11
great          10
get            10
sauce           9
calamari        9
ive             9
meal            8
service         8
little          8
amazing         8
one             8
experience      8
time            7
even            7
dish            7
dinner          7
entrees         7
make            7
also            6
gnocchi         6
delicious       6
back            6
dtype: int64

In [41]:
other_stop_words = ['one','came','even']

In [42]:
df['cleanreviews'] = df['stopwords'].apply(lambda x: " ".join(word for word in x.split() if word not in other_stop_words))

In [43]:
#df.head()

In [44]:
pd.Series(" ".join(df['cleanreviews']).split()).value_counts()[:30]

food           15
would          15
carmelinas     15
reservation    15
end            12
pasta          12
ordered        12
north          11
best           11
get            10
great          10
sauce           9
ive             9
calamari        9
meal            8
service         8
amazing         8
little          8
experience      8
time            7
entrees         7
make            7
dish            7
dinner          7
italian         6
delicious       6
also            6
got             6
go              6
good            6
dtype: int64

In [45]:
df['cleanreviews_word_count'] = df['stopwords'].apply(lambda x: len([word for word in x.split() if word not in other_stop_words]))

In [46]:
df['clean_rate'] =  df['cleanreviews_word_count'] / df['word_count']

In [47]:
df.head()

,reviews,word_count,char_count,average_word_length,stopword_count,stopword_rate,lowercase,punctuation,stopwords,cleanreviews,cleanreviews_word_count,clean_rate
0,"Your trust is our top concern, so businesses c...",18,100,4.611111,7,0.388889,"your trust is our top concern, so businesses c...",your trust is our top concern so businesses ca...,trust top concern businesses cant pay alter re...,trust top concern businesses cant pay alter re...,10,0.555556
1,Start your review of Carmelina's.,5,33,5.800000,2,0.400000,start your review of carmelina's.,start your review of carmelinas,start review carmelinas,start review carmelinas,3,0.600000
2,We had an amazing experience at Carmelina's! T...,141,795,4.645390,62,0.439716,we had an amazing experience at carmelina's! t...,we had an amazing experience at carmelinas tot...,amazing experience carmelinas totally would re...,amazing experience carmelinas totally would re...,73,0.517730
3,"Back in December, after multiple recommendatio...",554,3038,4.483755,280,0.505415,"back in december, after multiple recommendatio...",back in december after multiple recommendation...,back december multiple recommendations friends...,back december multiple recommendations friends...,262,0.472924
4,Pre-Covid Review: Came here to celebrate my gi...,38,233,5.157895,14,0.368421,pre-covid review: came here to celebrate my gi...,precovid review came here to celebrate my girl...,precovid review came celebrate girlfriends bir...,precovid review celebrate girlfriends birthday...,23,0.605263

In [48]:
#Lemmatization

In [49]:
#import textblob
from textblob import Word

In [50]:
df['lemmatized'] = df['cleanreviews'].apply(lambda x: " ".join(Word(word).lemmatize() for word in x.split()))

In [51]:
#df.head()

In [52]:
#(Markdown section) Sentiment Analysis

In [53]:
from textblob import TextBlob

In [54]:
df['polarity'] = df['lemmatized'].apply(lambda x: TextBlob(x).sentiment[0])

In [55]:
df['subjectivity'] = df['lemmatized'].apply(lambda x: TextBlob(x).sentiment[1])

In [56]:
df.head()

,reviews,word_count,char_count,average_word_length,stopword_count,stopword_rate,lowercase,punctuation,stopwords,cleanreviews,cleanreviews_word_count,clean_rate,lemmatized,polarity,subjectivity
0,"Your trust is our top concern, so businesses c...",18,100,4.611111,7,0.388889,"your trust is our top concern, so businesses c...",your trust is our top concern so businesses ca...,trust top concern businesses cant pay alter re...,trust top concern businesses cant pay alter re...,10,0.555556,trust top concern business cant pay alter remo...,0.500000,0.500000
1,Start your review of Carmelina's.,5,33,5.800000,2,0.400000,start your review of carmelina's.,start your review of carmelinas,start review carmelinas,start review carmelinas,3,0.600000,start review carmelinas,0.000000,0.000000
2,We had an amazing experience at Carmelina's! T...,141,795,4.645390,62,0.439716,we had an amazing experience at carmelina's! t...,we had an amazing experience at carmelinas tot...,amazing experience carmelinas totally would re...,amazing experience carmelinas totally would re...,73,0.517730,amazing experience carmelinas totally would re...,0.469375,0.493125
3,"Back in December, after multiple recommendatio...",554,3038,4.483755,280,0.505415,"back in december, after multiple recommendatio...",back in december after multiple recommendation...,back december multiple recommendations friends...,back december multiple recommendations friends...,262,0.472924,back december multiple recommendation friend t...,0.174674,0.481473
4,Pre-Covid Review: Came here to celebrate my gi...,38,233,5.157895,14,0.368421,pre-covid review: came here to celebrate my gi...,precovid review came here to celebrate my girl...,precovid review came celebrate girlfriends bir...,precovid review celebrate girlfriends birthday...,23,0.605263,precovid review celebrate girlfriend birthday ...,0.412500,0.725000

In [57]:
df.describe()

,word_count,char_count,average_word_length,stopword_count,stopword_rate,cleanreviews_word_count,clean_rate,polarity,subjectivity
count,22.000000,22.000000,22.000000,22.000000,22.000000,22.00000,22.000000,22.000000,22.000000
mean,123.954545,689.636364,4.695476,57.954545,0.439285,63.50000,0.538742,0.306567,0.564092
std,120.140187,655.934270,0.393999,61.424733,0.060155,56.81109,0.059045,0.150178,0.151813
min,5.000000,33.000000,4.000000,2.000000,0.311111,3.00000,0.444444,0.000000,0.000000
25%,41.250000,239.750000,4.489298,17.500000,0.401064,23.50000,0.501812,0.206550,0.506629
50%,94.500000,528.500000,4.652482,39.500000,0.443542,48.50000,0.526484,0.313636,0.596389
75%,159.750000,840.250000,4.904234,81.000000,0.489612,81.25000,0.587060,0.408085,0.636905
max,554.000000,3038.000000,5.800000,280.000000,0.543210,262.00000,0.649485,0.533333,0.750000

In [58]:
df.drop(['lowercase', 'punctuation', 'stopwords','cleanreviews', 'lemmatized'], axis=1, inplace=True)

In [59]:
df.sort_values(by='polarity')

,reviews,word_count,char_count,average_word_length,stopword_count,stopword_rate,cleanreviews_word_count,clean_rate,polarity,subjectivity
1,Start your review of Carmelina's.,5,33,5.800000,2,0.400000,3,0.600000,0.000000,0.000000
10,Expectations were far too high prior to coming...,82,508,5.207317,34,0.414634,49,0.597561,0.038929,0.420000
18,3.5*You should definitely make a reservation i...,253,1392,4.505929,128,0.505929,123,0.486166,0.125000,0.612635
5,"While visiting Boston, we decided to have lunc...",59,349,4.915254,28,0.474576,30,0.508475,0.140625,0.625000
3,"Back in December, after multiple recommendatio...",554,3038,4.483755,280,0.505415,262,0.472924,0.174674,0.481473
6,My true rating would be a 4.5!Ive attempted to...,222,1195,4.387387,112,0.504505,106,0.477477,0.195341,0.582500
19,Late flight (less than 50% full) arrival from ...,97,554,4.721649,33,0.340206,63,0.649485,0.240179,0.530952
7,"Great food, probably some of the best Chicken ...",45,257,4.733333,14,0.311111,29,0.644444,0.252778,0.750000
13,Carmelina's is my favorite restaurant in the N...,138,785,4.695652,60,0.434783,70,0.507246,0.291667,0.609444
21,The fettuccine Carmelina was perfecto! Great m...,37,223,5.027027,14,0.378378,23,0.621622,0.300000,0.648148
15,AMAZING FOOD!My go to place in the North End. ...,40,234,4.875000,17,0.425000,22,0.550000,0.308333,0.638095
12,We went for dinner the night after they reopen...,162,848,4.172840,88,0.543210,72,0.444444,0.318939,0.526515
20,Carmelina's is the number one restaurant in th...,190,1078,4.615789,85,0.447368,99,0.521053,0.344608,0.565686
16,Make a reservation or else you won't get to ea...,153,817,4.346405,69,0.450980,84,0.549020,0.353846,0.611538
9,My taste buds were in heaven after I finally e...,220,1237,4.627273,99,0.450000,118,0.536364,0.382553,0.693473
8,While passing by I couldn't help but notice th...,93,549,4.913978,46,0.494624,48,0.516129,0.394841,0.490873
4,Pre-Covid Review: Came here to celebrate my gi...,38,233,5.157895,14,0.368421,23,0.605263,0.412500,0.725000
14,Seriously a fantastic meal. We started with th...,96,498,4.197917,45,0.468750,48,0.500000,0.441026,0.583333
2,We had an amazing experience at Carmelina's! T...,141,795,4.645390,62,0.439716,73,0.517730,0.469375,0.493125
0,"Your trust is our top concern, so businesses c...",18,100,4.611111,7,0.388889,10,0.555556,0.500000,0.500000
17,"BEST Italian in the North End, Hands Down. Eve...",47,265,4.659574,19,0.404255,25,0.531915,0.525926,0.688889
11,Amazing food and service! I can see why they a...,37,184,4.000000,19,0.513514,17,0.459459,0.533333,0.633333

In [60]:
df.head()

,reviews,word_count,char_count,average_word_length,stopword_count,stopword_rate,cleanreviews_word_count,clean_rate,polarity,subjectivity
0,"Your trust is our top concern, so businesses c...",18,100,4.611111,7,0.388889,10,0.555556,0.500000,0.500000
1,Start your review of Carmelina's.,5,33,5.800000,2,0.400000,3,0.600000,0.000000,0.000000
2,We had an amazing experience at Carmelina's! T...,141,795,4.645390,62,0.439716,73,0.517730,0.469375,0.493125
3,"Back in December, after multiple recommendatio...",554,3038,4.483755,280,0.505415,262,0.472924,0.174674,0.481473
4,Pre-Covid Review: Came here to celebrate my gi...,38,233,5.157895,14,0.368421,23,0.605263,0.412500,0.725000